web:
  - changed-files:
      - any-glob-to-any-file: packages/web/**/*
api:
  - changed-files:
      - any-glob-to-any-file: packages/api/**/*
chore:
  - changed-files:
      - any-glob-to-any-file:
          - libs/**/*
          - tools/**/*
          - .github/**/*
