packages:
  - packages/*
  - libs/*
  - tools/*

shamefullyHoist: true

overrides:
  "@babel/core@<8": ^7.29.7
  "@sigstore/core@<4": ^3.2.1
  "@sigstore/verify@<4": ^3.1.1
  "@types/react": 19.2.14
  baseline-browser-mapping@<3: ^2.11.24
  brace-expansion@<2: ^1.1.21
  brace-expansion@>=3 <6: ^5.0.9
  browserslist@<5: ^4.28.7
  cookie: 0.7.0
  esbuild@>=0.27.3 <0.28.1: 0.28.2
  fast-uri@<4: ^3.1.8
  follow-redirects@<2: ^1.16.0
  ip-address@<11: ^10.3.1
  joi@<18: ^17.13.8
  joi@>=18 <19: ^18.2.9
  js-yaml@<4: ^3.15.2
  js-yaml@>=4 <5: ^4.3.2
  lodash: ^4.18.1
  minimatch@<4: 3.1.4
  minimatch@>=9 <10: 9.0.7
  nanoid@<4: ^3.3.19
  picomatch@<3: ^2.3.2
  postcss@<9: ^8.5.28
  qs@<7: ^6.16.0
  sharp@<1: ^0.35.4
  sigstore@<5: ^4.1.1
  smol-toml@<2: ^1.8.0
  tar: ^7.5.22
  tmp: ^0.2.7
  typescript: 5.9.3
  uuid@<11.1.1: ^11.1.1
  vite: 6.4.3
  yaml@>=2 <3: ^2.9.1
