module.exports = {
  "demo-demo": {
    input: {
      target: "../../document/api/services/demo/openapi.yaml",
    },
    output: {
      mode: "tags-split",
      target: "../../packages/api/lib/demo",
      schemas: "../../packages/api/lib/demo/model",
      client: "react-query",
      mock: true,
      clean: true,
      headers: true,
      override: {
        header,
        mutator: {
          path: "../../packages/api/lib/demoHttpClient.ts",
          name: "demoHttpClient",
        },
      },
    },
  },
};

function header(info) {
  return [
    "eslint-disable @typescript-eslint/explicit-function-return-type",
    "Generated by orval 🍺",
    "Do not edit manually.",
    ...(info.title ? [info.title] : []),
    ...(info.description ? [info.description] : []),
    ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
  ];
}
