/* eslint-disable @typescript-eslint/explicit-function-return-type */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * TodoApi
 * OpenAPI spec version: 1.0.0
 */

export interface Todo {
  todo_id: number;
  description: string;
  end_date: string;
  completed: boolean;
}
