openapi: 3.0.0
info:
  title: TodoApi
  version: 1.0.0
servers:
  - url: https://api-dev.server
  - url: https://api.server
tags: []
paths:
  /todos:
    get:
      tags:
        - todo
      operationId: getTodos
      description: get todos
      security:
        - Bearer: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Todo"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                code: 404
                message: Not Found
  /todo:
    post:
      tags:
        - todo
      operationId: registerTodo
      description: register todo
      security:
        - Bearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TodoRegisterble"
      responses:
        "201":
          description: Registerd
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                code: 400
                message: Bad Request
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                code: 500
                message: Internal Server Error
  /todo/{todo_id}:
    get:
      tags:
        - todo
      operationId: getTodo
      description: get todo
      security:
        - Bearer: []
      parameters:
        - in: path
          name: todo_id
          description: ""
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                code: 404
                message: Not Found
    put:
      tags:
        - todo
      operationId: updateTodo
      description: update todo
      security:
        - Bearer: []
      parameters:
        - in: path
          name: todo_id
          description: ""
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TodoUpdatable"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                code: 404
                message: Not Found
    delete:
      tags:
        - todo
      operationId: deleteTodo
      description: delete todo
      security:
        - Bearer: []
      parameters:
        - in: path
          name: todo_id
          description: ""
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Success
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                code: 400
                message: Bad Request
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                code: 404
                message: Not Found
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                code: 500
                message: Internal Server Error
components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
    Todo:
      required:
        - todo_id
        - description
        - end_date
        - completed
      properties:
        todo_id:
          type: integer
          example: 1
        description:
          type: string
          example: todo action message
        end_date:
          type: string
          format: date-time
          example: "2022-12-12T10:00:00+09:00"
        completed:
          type: boolean
          example: false
    TodoRegisterble:
      required:
        - description
        - end_date
      properties:
        description:
          type: string
          example: todo action message
        end_date:
          type: string
          format: date-time
          example: "2022-12-12T10:00:00+09:00"
    TodoUpdatable:
      required:
        - description
        - end_date
        - completed
      properties:
        description:
          type: string
          example: todo action message
        end_date:
          type: string
          format: date-time
          example: "2022-12-12T10:00:00+09:00"
        completed:
          type: boolean
          example: false
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
