name: triage issue via Claude Code
on:
  issues:
    types: [opened]

jobs:
  triage-issue:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup GitHub MCP
        run: |
          mkdir -p /tmp/mcp-config
          cat > /tmp/mcp-config/mcp-servers.json << 'EOF'
          {
            "github": {
              "command": "docker",
              "args": [
                "run",
                "-i",
                "--rm",
                "-e",
                "GITHUB_PERSONAL_ACCESS_TOKEN",
                "ghcr.io/github/github-mcp-server:sha-7aced2b"
              ],
              "env": {
                "GITHUB_PERSONAL_ACCESS_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
              }
            }
          }
          EOF

      - name: create triage prompt
        run: |
          mkdir -p /tmp/claude-prompts
          cat > /tmp/claude-prompts/triage-prompt.txt << 'EOF'
          あなたはGitHub Issueの選別アシスタントです。あなたの任務はIssueを分析し、提供されたリストから適切なラベルを選択することです。

          重要: Issueにコメントやメッセージを投稿しないでください。あなたの唯一の行動はラベルを適用することだけです。

          Issue情報:
          - リポジトリ: ${{ github.repository }}
          - Issue番号: ${{ github.event.issue.number }}

          タスク概要:

          1. まず、`gh label list`を実行して、このリポジトリで使用可能なラベルのリストを取得してください。他には何も実行せず、このコマンドだけを実行してください。

          2. 次に、GitHubツールを使用してIssueのコンテキストを取得してください:
             - 以下のツールにアクセスできます:
               - mcp__github__get_issue: タイトル、説明、既存のラベルなど、現在のIssueの詳細を取得するために使用します
               - mcp__github__get_issue_comments: コメントで提供されるディスカッションや追加のコンテキストを読むために使用します
               - mcp__github__update_issue: Issueにラベルを適用するために使用します（コメント投稿には使用しないでください）
               - mcp__github__search_issues: 適切な分類のためのコンテキストを提供し、潜在的な重複Issueを特定するために、類似のIssueを見つけるために使用します
               - mcp__github__list_issues: 他のIssueがどのようにラベル付けされているかのパターンを理解するために使用します
             - まず、mcp__github__get_issueを使用してIssueの詳細を取得することから始めてください

          3. Issueの内容を分析してください。以下の点を考慮してください:
             - Issueのタイトルと説明
             - Issueの種類（バグレポート、機能リクエスト、質問など）
             - 言及された技術分野
             - 重大度または優先度の指標
             - ユーザーへの影響
             - 影響を受けるコンポーネント

          4. 上記で提供された利用可能なラベルのリストから適切なラベルを選択してください:
             - Issueの性質を正確に反映するラベルを選択してください
             - 具体的かつ包括的にしてください
             - 緊急性を判断できる場合は、優先度ラベル（high-priority、med-priority、low-priority）を選択してください
             - 該当する場合は、プラットフォームラベル（android、ios）を検討してください
             - mcp__github__search_issuesを使用して類似のIssueを見つけた場合は、適切であれば「duplicate」ラベルの使用を検討してください。ただし、そのIssueが他のオープンなIssueの重複である場合にのみ行ってください。

          5. 選択したラベルを適用してください:
             - mcp__github__update_issueを使用して、選択したラベルを適用してください
             - あなたの決定を説明するコメントを投稿しないでください
             - ユーザーと直接やり取りしないでください
             - 明確に適用できるラベルがない場合は、ラベルを適用しないでください

          重要なガイドライン:
          - 分析を徹底的に行ってください
          - 上記の提供されたリストからのみラベルを選択してください
          - Issueにコメントを投稿しないでください
          - あなたの唯一の行動はmcp__github__update_issueを使用してラベルを適用することだけです
          - 明確に適用できるラベルがない場合は、ラベルを追加しなくても問題ありません
          EOF

      - name: Run Claude code for triage
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt_file: /tmp/claude-prompts/triage-prompt.txt
          allowed_tools: "Bash(gh label list),mcp__github__get_issue,mcp__github__get_issue_comments,mcp__github__update_issue,mcp__github__search_issues,mcp__github__list_issues"
          mcp_config: /tmp/mcp-config/mcp-servers.json
          timeout_minutes: "5"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
